### ISSUE TITLE
Error inflating class net.dhleong.vlcvideoview.VlcVideoView

### ISSUE THREAD

**Issue by estebandres** [dhleong/vlc-video-view#2]
Hello, I have included VlcVideoView on a fragment xml layout file. 
```xml
<LinearLayout
android:layout_width="match_parent"
android:layout_height="wrap_content"
android:orientation="vertical"
android:paddingBottom="10dp"
android:paddingEnd="10dp"
android:paddingStart="10dp">

	<TextView
	    android:layout_width="match_parent"
	    android:layout_height="wrap_content"
	    android:paddingBottom="5dp"
	    android:paddingTop="5dp"
	    android:text="GENERAL"
	    android:textAppearance="@style/TextAppearance.AppCompat.Small"
	    android:textStyle="bold" />

	<net.dhleong.vlcvideoview.VlcVideoView
	    android:id="@+id/ip_camera_video"
	    android:layout_width="match_parent"
	    android:layout_height="wrap_content"
	    android:layout_margin="8dp"
	    android:gravity="center"
	    android:keepScreenOn="true"
	    />
</LinearLayout>
```
But when the fragments is created (onCreateView) and tries to inflate the view this exceptions is thrown.

```java
2019-03-20 16:15:26.539 23827-23827/com.urbit_iot.porton.prod.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.urbit_iot.porton.prod.debug, PID: 23827
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.urbit_iot.porton.prod.debug/com.urbit_iot.porton.umodconfig.UModConfigActivity}: android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class net.dhleong.vlcvideoview.VlcVideoView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2762)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2823)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class net.dhleong.vlcvideoview.VlcVideoView
     Caused by: android.view.InflateException: Binary XML file line #60: Error inflating class net.dhleong.vlcvideoview.VlcVideoView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.view.LayoutInflater.createView(LayoutInflater.java:645)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at com.urbit_iot.porton.umodconfig.UModConfigFragment.onCreateView(UModConfigFragment.java:206)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2439)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1460)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:620)
2019-03-20 16:15:26.539 23827-23827/com.urbit_iot.porton.prod.debug E/AndroidRuntime:     at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
        at android.app.Activity.performStart(Activity.java:6789)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2725)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2823)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6349)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/videolan/libvlc/IVLCVout$Callback;
        	... 46 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.videolan.libvlc.IVLCVout$Callback" on path: DexPathList[[zip file "/data/app/com.urbit_iot.porton.prod.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.urbit_iot.porton.prod.debug-2/lib/arm, /data/app/com.urbit_iot.porton.prod.debug-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 46 more
```  
To include the library to my project I only added this single line on the gradle file:
```groovy
implementation "com.github.dhleong:vlc-video-view:0.5.0"
```

**Comment by dhleong** [comment]
This seems to be the root error here:

```
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.videolan.libvlc.IVLCVout$Callback" on path: DexPathList[[zip file "/data/app/com.urbit_iot.porton.prod.debug-2/base.apk"],nativeLibraryDirectories=[/data/app/com.urbit_iot.porton.prod.debug-2/lib/arm, /data/app/com.urbit_iot.porton.prod.debug-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```

which suggests the VLC library isn't packaged in the dex file. Maybe check your dependencies (run something like `gradle app:dep` to make sure that `de.mrmaffen:vlc-android-sdk:2.0.6` is somewhere on there, and add it explicitly if not.

**Comment by estebandres** [comment]
Thank you for the prompt response.
Indeed including `de.mrmaffen:vlc-android-sdk:2.0.6` solved the issue.
